'use client'
import { useState } from 'react'
import { createFlat, joinFlat } from '@/app/actions'
import { useRouter } from 'next/navigation'

export default function OnboardingPage() {
  const [mode,setMode]=useState<'create'|'join'>('create'); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const router=useRouter()
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const f=new FormData(e.currentTarget); try { if(mode==='create') await createFlat({name:String(f.get('name')||''),address:String(f.get('address')||''),monthStartDay:Number(f.get('monthStartDay')||1),mealPolicy:(String(f.get('mealPolicy')) as 'opt_in'|'opt_out')}); else await joinFlat(String(f.get('inviteCode')||'')); router.push('/dashboard'); router.refresh() } catch(err) { setError(err instanceof Error ? err.message : 'Could not continue') } finally { setBusy(false) } }
  return <div className="mx-auto mt-12 max-w-xl card"><div className="mb-5 flex gap-2"><button className={mode==='create'?'btn-primary':'btn-secondary'} onClick={()=>setMode('create')}>Create a flat</button><button className={mode==='join'?'btn-primary':'btn-secondary'} onClick={()=>setMode('join')}>Join with code</button></div>{mode==='create'?<form onSubmit={submit} className="space-y-4"><input name="name" className="input" placeholder="Flat / mess name" required/><input name="address" className="input" placeholder="Address (optional)"/><select name="monthStartDay" className="input" defaultValue="1">{[1,5,10,15,20,25].map(d=><option key={d} value={d}>Cycle starts on day {d}</option>)}</select><select name="mealPolicy" className="input" defaultValue="opt_out"><option value="opt_out">Opt-out — counted unless skipped</option><option value="opt_in">Opt-in — only counted when confirmed</option></select><button className="btn-primary w-full" disabled={busy}>{busy?'Creating…':'Create flat'}</button></form>:<form onSubmit={submit} className="space-y-4"><input name="inviteCode" className="input text-center uppercase tracking-[0.3em]" placeholder="8-character invite code" maxLength={16} required/><button className="btn-primary w-full" disabled={busy}>{busy?'Joining…':'Join flat'}</button></form>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</div>
}
