(() => {
  const state = { active:false, audience:'all', batchId:'', channel:'whatsapp', title:'', body:'', campaigns:[], selectedIds:[] };
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const role=()=>window.profile?.role||'';
  const canWrite=()=>['owner','admin','staff'].includes(role());
  const students=()=>window.data?.students||[];
  const batches=()=>window.data?.batches||[];
  const phone=s=>(s.guardian_phone||s.phone||'').trim();
  const audienceStudents=()=>state.audience==='batch'?students().filter(s=>s.batch_id===state.batchId):state.audience==='students'?students().filter(s=>state.selectedIds.includes(s.id)):students();
  const personalize=(body,s)=>body.replaceAll('{{student}}',s.name||'Student').replaceAll('{{guardian}}',s.guardian_name||'Guardian').replaceAll('{{batch}}',s.batches?.name||batches().find(b=>b.id===s.batch_id)?.name||'your batch').replaceAll('{{center}}',window.profile?.organizations?.name||'EduFlow');
  async function loadCampaigns(){const {data,error}=await window.client().from('communication_campaigns').select('id,title,body,channel,audience_type,batch_id,status,created_at').eq('organization_id',window.orgId()).order('created_at',{ascending:false});if(error)throw error;state.campaigns=data||[]}
  function openComposer(){if(!canWrite())return window.toast?.('Only owners, admins, and staff can prepare messages.');state.selectedIds=[];window.modal('New communication',composerHtml());syncComposer()}
  function composerHtml(){return `<div class="form-grid"><div class="field"><label>Title</label><input id="cm_title" placeholder="Fee reminder"></div><div class="field"><label>Channel</label><select id="cm_channel" onchange="syncComposer()"><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="notice">Internal notice</option></select></div><div class="field"><label>Audience</label><select id="cm_audience" onchange="syncComposer()"><option value="all">All guardians</option><option value="batch">One batch</option><option value="students">Selected students</option></select></div><div class="field" id="cm_batch_wrap"><label>Batch</label><select id="cm_batch">${batches().map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></div></div><div id="cm_students_wrap" style="margin-top:14px"></div><div class="field" style="margin-top:14px"><label>Message</label><textarea id="cm_body" rows="8" placeholder="Dear {{guardian}}, {{student}}'s monthly fee is due…"></textarea><div class="subtitle">Variables: {{student}}, {{guardian}}, {{batch}}, {{center}}</div></div><div class="actions end-actions"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="prepareCommunication()">Prepare message</button></div>`}
  function syncComposer(){const a=document.getElementById('cm_audience'),b=document.getElementById('cm_batch_wrap'),s=document.getElementById('cm_students_wrap');if(!a)return;state.audience=a.value;state.batchId=document.getElementById('cm_batch')?.value||state.batchId;if(b)b.style.display=state.audience==='batch'?'':'none';if(s)s.innerHTML=state.audience==='students'?`<div class="card"><div class="subtitle" style="margin-bottom:8px">Select recipients</div>${students().map(x=>`<label style="display:flex;gap:8px;align-items:center;padding:6px 0"><input type="checkbox" class="cm-student" value="${x.id}"> ${esc(x.name)} <span class="subtitle">${esc(phone(x)||'No phone')}</span></label>`).join('')||'<div class="empty">No students.</div>'}</div>`:''}
  async function prepareCommunication(){try{if(!canWrite())throw new Error('You do not have permission to prepare messages.');const title=document.getElementById('cm_title').value.trim(),body=document.getElementById('cm_body').value.trim(),channel=document.getElementById('cm_channel').value;if(!title||!body)throw new Error('Title and message are required.');state.title=title;state.body=body;state.channel=channel;state.audience=document.getElementById('cm_audience').value;state.batchId=document.getElementById('cm_batch')?.value||'';state.selectedIds=[...document.querySelectorAll('.cm-student:checked')].map(x=>x.value);if(state.audience==='students'&&!state.selectedIds.length)throw new Error('Select at least one student.');const targets=audienceStudents().map(s=>({student:s,phone:phone(s)})).filter(x=>x.phone);if(!targets.length)throw new Error('No matching recipients have a phone number.');window.modal('Review & prepare',reviewHtml(targets))}catch(e){window.toast?.(e.message)}}
  function reviewHtml(targets){return `<div class="notice">This step prepares recipient-specific text. No message is sent automatically.</div><div class="card" style="margin-top:12px"><div class="section-head"><div><h2>${esc(state.title)}</h2><div class="subtitle">${targets.length} recipients • ${esc(state.channel)}</div></div><span class="badge badge-blue">Copy ready</span></div><div style="margin-top:12px;padding:14px;background:#f8fafc;border:1px solid var(--line);border-radius:12px;white-space:pre-wrap;font-size:13px">${esc(personalize(state.body,targets[0].student))}</div></div><div class="actions end-actions"><button class="btn btn-secondary" onclick="closeModal();openComposer()">Back</button><button class="btn btn-primary" onclick="saveCommunication()">Save & prepare messages</button></div>`}
  async function saveCommunication(){try{const targets=audienceStudents().map(s=>({student:s,phone:phone(s)})).filter(x=>x.phone);const payload={organization_id:window.orgId(),title:state.title,body:state.body,channel:state.channel,audience_type:state.audience,batch_id:state.audience==='batch'?state.batchId:null,status:'prepared'};const {data,error}=await window.client().from('communication_campaigns').insert(payload).select().single();if(error)throw error;const rows=targets.map(x=>({organization_id:window.orgId(),campaign_id:data.id,student_id:x.student.id,recipient_name:x.student.guardian_name||x.student.name,recipient_phone:x.phone,recipient_type:x.student.guardian_phone?'guardian':'student'}));const {error:re}=await window.client().from('communication_recipients').insert(rows);if(re)throw re;closeModal();await loadCampaigns();render();window.toast?.('Messages prepared.');setTimeout(()=>openCampaign(data.id),100)}catch(e){window.toast?.(e.message)}}
  async function openCampaign(id){try{const {data:campaign,error}=await window.client().from('communication_campaigns').select('*').eq('organization_id',window.orgId()).eq('id',id).single();if(error)throw error;const {data:recipients,error:re}=await window.client().from('communication_recipients').select('recipient_name,recipient_phone,recipient_type,student_id').eq('organization_id',window.orgId()).eq('campaign_id',id);if(re)throw re;const example=recipients?.[0],student=students().find(s=>s.id===example?.student_id),text=student?personalize(campaign.body,student):campaign.body;window.modal(`Communication • ${esc(campaign.title)}`,`<div class="notice">Prepared only. Sending is not connected to an external messaging provider yet.</div><div class="card" style="margin-top:12px"><div class="subtitle">Example message for ${esc(example?.recipient_name||'recipient')}</div><div style="margin-top:8px;white-space:pre-wrap;background:#f8fafc;border:1px solid var(--line);padding:12px;border-radius:10px">${esc(text)}</div><div class="actions" style="margin-top:12px"><button class="btn btn-primary" onclick="copyCommunication(${JSON.stringify(text)})">Copy message</button>${campaign.channel==='whatsapp'?`<a class="btn btn-secondary" href="https://wa.me/${encodeURIComponent((example?.recipient_phone||'').replace(/\D/g,''))}" target="_blank" rel="noopener">Open WhatsApp</a>`:''}</div></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>Recipient</th><th>Phone</th><th>Type</th></tr></thead><tbody>${(recipients||[]).map(r=>`<tr><td>${esc(r.recipient_name||'—')}</td><td>${esc(r.recipient_phone||'—')}</td><td>${esc(r.recipient_type)}</td></tr>`).join('')}</tbody></table></div>`)}catch(e){window.toast?.(e.message)}}
  async function copyCommunication(text){try{await navigator.clipboard.writeText(text);window.toast?.('Message copied.')}catch(e){window.toast?.('Copy failed; select the text manually.')}}
  function kpi(label,value,note,icon){return `<div class="card stat"><div><div class="label">${label}</div><div class="value">${value}</div><div class="subtitle">${note}</div></div><div class="iconbox">${icon}</div></div>`}
  function view(){const rows=state.campaigns.map(c=>`<div class="list-item"><div><strong>${esc(c.title)}</strong><div class="subtitle">${esc(c.channel)} • ${esc(c.audience_type)} • ${new Date(c.created_at).toLocaleDateString('en-BD')}</div></div><button class="btn btn-secondary btn-sm" onclick="openCampaign('${c.id}')">View</button></div>`).join('')||'<div class="empty">No prepared messages yet.</div>';return `<div class="page-head"><div><h1>Communication</h1><div class="subtitle">Prepare targeted guardian/student messages without sending anything accidentally.</div></div>${canWrite()?`<button class="btn btn-primary" onclick="openComposer()">＋ New message</button>`:''}</div><div class="grid grid-3">${kpi('Students',students().length,'available recipients','♙')}${kpi('Guardians',students().filter(s=>s.guardian_phone).length,'with guardian phone','☎')}${kpi('Prepared',state.campaigns.length,'message campaigns','✉')}</div><div class="card" style="margin-top:16px"><div class="section-head"><div><h2>Recent campaigns</h2><div class="subtitle">Saved message sets and recipient groups.</div></div></div><div class="list">${rows}</div></div>`}
  function render(){const c=document.getElementById('content');if(c&&state.active){c.innerHTML=view();setTimeout(loadCampaignsView,0)}}
  async function loadCampaignsView(){try{await loadCampaigns();const c=document.getElementById('content');if(c&&state.active)c.innerHTML=view()}catch(e){const c=document.getElementById('content');if(c)c.innerHTML=`<div class="card"><div class="notice">${esc(e.message)}</div></div>`}}
  const originalGo=window.go;window.go=function(p){state.active=p==='communication';const r=originalGo.apply(this,arguments);if(state.active)setTimeout(render,0);return r};
  Object.assign(window,{openComposer,prepareCommunication,saveCommunication,openCampaign,copyCommunication,syncComposer});
})();