(() => {
  const state={active:false,month:new Date().toISOString().slice(0,7),invoices:[],payments:[],currentRole:''};
  const money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const monthDate=()=>`${state.month}-01`;
  const monthLabel=()=>new Date(`${state.month}-01T00:00:00`).toLocaleDateString('en-BD',{month:'long',year:'numeric'});
  const canWrite=()=>['owner','admin','staff'].includes(state.currentRole);
  const canInvoice=()=>['owner','admin'].includes(state.currentRole);
  async function getRole(){const {data:auth,error:ae}=await window.client().auth.getUser();if(ae)throw ae;if(!auth.user)throw new Error('Your session has expired.');const {data,error}=await window.client().from('profiles').select('role').eq('id',auth.user.id).single();if(error)throw error;state.currentRole=data?.role||'';return state.currentRole;}
  function nextMonth(){const d=new Date(`${state.month}-01T00:00:00`);d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,7)}
  async function loadLedger(){const o=window.orgId?.();if(!o)throw new Error('Workspace is not ready.');await getRole();const [i,p]=await Promise.all([window.client().from('fee_invoices').select('id,student_id,billing_month,amount_due,discount,note,status,students(name,student_code,monthly_fee,guardian_phone)').eq('organization_id',o).eq('billing_month',monthDate()).order('created_at',{ascending:false}),window.client().from('fee_payments').select('id,invoice_id,student_id,amount,payment_method,receipt_no,paid_at,reference,note,students(name,student_code)').eq('organization_id',o).gte('paid_at',`${state.month}-01T00:00:00.000Z`).lt('paid_at',`${nextMonth()}-01T00:00:00.000Z`).order('paid_at',{ascending:false})]);if(i.error)throw i.error;if(p.error)throw p.error;state.invoices=i.data||[];state.payments=p.data||[]}
  function invoiceBalance(inv){const paid=state.payments.filter(p=>p.invoice_id===inv.id).reduce((n,p)=>n+Number(p.amount||0),0);return Math.max(0,Number(inv.amount_due||0)-Number(inv.discount||0)-paid)}
  async function generateMonth(){await getRole();if(!canInvoice())throw new Error('Only owners and admins can generate monthly fees.');const o=window.orgId();const {data:students,error:se}=await window.client().from('students').select('id,monthly_fee').eq('organization_id',o);if(se)throw se;if(!students?.length)throw new Error('Add students before generating monthly fees.');const rows=students.map(s=>({organization_id:o,student_id:s.id,billing_month:monthDate(),amount_due:Math.max(0,Number(s.monthly_fee||0)),discount:0,status:'open'}));const {error}=await window.client().from('fee_invoices').upsert(rows,{onConflict:'student_id,billing_month',ignoreDuplicates:true});if(error)throw error;await loadLedger();render();window.toast?.(`Monthly fees generated for ${monthLabel()}.`)}
  function kpi(label,value,note,icon){return `<div class="card stat"><div><div class="label">${label}</div><div class="value">${value}</div><div class="subtitle">${note}</div></div><div class="iconbox">${icon}</div></div>`}
  function ledgerView(){const totalDue=state.invoices.reduce((n,i)=>n+Math.max(0,Number(i.amount_due||0)-Number(i.discount||0)),0),totalPaid=state.payments.reduce((n,p)=>n+Number(p.amount||0),0),totalOutstanding=state.invoices.reduce((n,i)=>n+invoiceBalance(i),0),action=canInvoice()?`<button class="btn btn-primary" onclick="generateMonthlyFees()">＋ Generate this month</button>`:`<span class="badge badge-gray">Invoices read-only</span>`;return `<div class="page-head"><div><h1>Fees & Payments</h1><div class="subtitle">Monthly dues, partial payments, balances and receipts.</div></div><div class="actions"><input id="feeMonth" type="month" value="${state.month}" onchange="changeFeeMonth(this.value)">${action}${canWrite()?`<button class="btn btn-secondary" onclick="openLedgerPayment()">＋ Record payment</button>`:''}</div></div><div class="grid grid-3">${kpi('Monthly due',money(totalDue),`${state.invoices.length} invoices`,'৳')}${kpi('Collected',money(totalPaid),`${state.payments.length} payments`,'✓')}${kpi('Outstanding',money(totalOutstanding),'current balance','!')}</div><div class="card" style="margin-top:16px"><div class="section-head"><div><h2>${esc(monthLabel())} invoices</h2><div class="subtitle">Each student has one monthly invoice.</div></div><span class="badge badge-blue">${state.invoices.length}</span></div><div class="table-wrap" style="margin-top:12px"><table><thead><tr><th>Student</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>${state.invoices.map(i=>{const due=Math.max(0,Number(i.amount_due||0)-Number(i.discount||0)),paid=Math.max(0,due-invoiceBalance(i));return `<tr><td><strong>${esc(i.students?.name||'Student')}</strong><div class="subtitle">${esc(i.students?.student_code||'')}</div></td><td>${money(due)}</td><td>${money(paid)}</td><td><strong>${money(invoiceBalance(i))}</strong></td><td><span class="badge ${i.status==='paid'?'badge-success':i.status==='partial'?'badge-warning':i.status==='void'?'badge-danger':'badge-blue'}">${esc(i.status)}</span></td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" onclick="viewLedgerInvoice('${i.id}')">View</button>${invoiceBalance(i)>0&&canWrite()?`<button class="btn btn-primary btn-sm" onclick="openLedgerPayment('${i.id}')">Pay</button>`:''}</div></td></tr>`}).join('')||'<tr><td colspan="6"><div class="empty">No invoices for this month. Use “Generate this month” to create them.</div></td></tr>'}</tbody></table></div></div>`}
  function render(){const c=document.getElementById('content');if(!c||!state.active)return;c.innerHTML=ledgerView();setTimeout(loadLedgerView,0)}
  async function loadLedgerView(){try{await loadLedger();const c=document.getElementById('content');if(c&&state.active)c.innerHTML=ledgerView()}catch(e){const c=document.getElementById('content');if(c)c.innerHTML=`<div class="card"><div class="notice">${esc(e.message)}</div></div>`}}
  async function changeFeeMonth(value){if(!/^\d{4}-\d{2}$/.test(value))return;state.month=value;await loadLedgerView()}
  async function openLedgerPayment(invoiceId=''){await getRole();if(!canWrite())return window.toast?.('You do not have permission to record payments.');const inv=invoiceId?state.invoices.find(i=>i.id===invoiceId):state.invoices.find(i=>invoiceBalance(i)>0);if(!inv)return window.toast?.('Create monthly invoices first.');const bal=invoiceBalance(inv);window.modal('Record payment',`<div class="notice"><strong>${esc(inv.students?.name||'Student')}</strong> • ${esc(monthLabel())}<br>Balance: <strong>${money(bal)}</strong></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Amount</label><input id="lf_amount" type="number" min="1" max="${bal}" value="${bal}"></div><div class="field"><label>Method</label><select id="lf_method"><option>bKash</option><option>Nagad</option><option>Cash</option><option>Bank</option></select></div><div class="field"><label>Receipt number</label><input id="lf_receipt" value="RCP-${Date.now().toString().slice(-8)}"></div><div class="field"><label>Reference</label><input id="lf_ref" placeholder="Transaction ID / note"></div></div><div class="actions end-actions"><button class="btn btn-secondary" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveLedgerPayment('${inv.id}')">Save payment</button></div>`)}
  async function saveLedgerPayment(invoiceId){try{await getRole();if(!canWrite())throw new Error('You do not have permission to record payments.');const inv=state.invoices.find(i=>i.id===invoiceId);if(!inv)throw new Error('Invoice not found.');const amount=Number(document.getElementById('lf_amount').value||0),bal=invoiceBalance(inv);if(amount<=0||amount>bal)throw new Error('Payment must be greater than 0 and no more than the current balance.');const payload={organization_id:window.orgId(),invoice_id:invoiceId,student_id:inv.student_id,amount,payment_method:document.getElementById('lf_method').value,receipt_no:document.getElementById('lf_receipt').value.trim(),reference:document.getElementById('lf_ref').value.trim()||null};if(!payload.receipt_no)throw new Error('Receipt number is required.');const {error}=await window.client().from('fee_payments').insert(payload);if(error)throw error;window.closeModal();await loadLedger();render();window.toast?.('Payment recorded.');setTimeout(()=>printLedgerReceipt(payload.receipt_no),150)}catch(e){window.toast?.(e.message)}}
  function viewLedgerInvoice(invoiceId){const inv=state.invoices.find(i=>i.id===invoiceId);if(!inv)return;const payments=state.payments.filter(p=>p.invoice_id===invoiceId),due=Math.max(0,Number(inv.amount_due||0)-Number(inv.discount||0)),paid=payments.reduce((n,p)=>n+Number(p.amount||0),0),bal=Math.max(0,due-paid);window.modal(`Invoice • ${esc(inv.students?.name||'Student')}`,`<div class="grid grid-3"><div class="card"><div class="subtitle">Due</div><strong>${money(due)}</strong></div><div class="card"><div class="subtitle">Paid</div><strong>${money(paid)}</strong></div><div class="card"><div class="subtitle">Balance</div><strong>${money(bal)}</strong></div></div><div class="card" style="margin-top:12px"><h2>Payment history</h2><div class="list">${payments.map(p=>`<div class="list-item"><div><strong>${money(p.amount)}</strong><div class="subtitle">${esc(p.payment_method)} • ${new Date(p.paid_at).toLocaleDateString('en-BD')} • ${esc(p.receipt_no)}</div></div><button class="btn btn-secondary btn-sm" onclick="printLedgerReceipt('${esc(p.receipt_no)}')">Receipt</button></div>`).join('')||'<div class="empty">No payments yet.</div>'}</div></div>`)}
  function printLedgerReceipt(receiptNo){const p=state.payments.find(x=>x.receipt_no===receiptNo);if(!p)return window.toast?.('Receipt not found.');const inv=state.invoices.find(x=>x.id===p.invoice_id),student=inv?.students,html=`<html><head><title>${esc(receiptNo)} • EduFlow</title><style>body{font-family:Arial,sans-serif;padding:32px;max-width:520px;margin:auto;color:#111}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:12px;margin-bottom:20px}.muted{color:#666;font-size:12px}table{width:100%;border-collapse:collapse}td{padding:8px 0;border-bottom:1px solid #ddd}.total{font-size:24px;font-weight:800}footer{margin-top:30px;color:#666;font-size:11px}</style></head><body><div class="head"><div><strong>EduFlow</strong><div class="muted">Coaching Center Payment Receipt</div></div><strong>${esc(receiptNo)}</strong></div><p><strong>${esc(student?.name||'Student')}</strong><br><span class="muted">${esc(student?.student_code||'')}</span></p><table><tr><td>Billing month</td><td>${esc(monthLabel())}</td></tr><tr><td>Payment method</td><td>${esc(p.payment_method)}</td></tr><tr><td>Payment date</td><td>${new Date(p.paid_at).toLocaleString('en-BD')}</td></tr><tr><td>Reference</td><td>${esc(p.reference||'—')}</td></tr><tr><td><strong>Amount paid</strong></td><td class="total">${money(p.amount)}</td></tr></table><footer>Generated by EduFlow • Keep this receipt for your records.</footer><script>window.onload=()=>{window.print();setTimeout(()=>window.close(),400)}</script></body></html>`;const w=window.open('','_blank','width=620,height=760');if(!w)return window.toast?.('Please allow pop-ups to print receipts.');w.document.write(html);w.document.close()}
  const originalGo=window.go,originalRefresh=window.refresh;
  window.go=function(p){state.active=p==='fees';const result=originalGo.apply(this,arguments);if(state.active)setTimeout(render,0);return result};
  window.refresh=async function(){const result=await originalRefresh.apply(this,arguments);if(state.active)setTimeout(render,0);return result};
  Object.assign(window,{generateMonthlyFees:generateMonth,changeFeeMonth,openLedgerPayment,saveLedgerPayment,viewLedgerInvoice,printLedgerReceipt});
})();