(() => {
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  const money=v=>'৳'+Number(v||0).toLocaleString('en-BD');
  const state={rules:[],events:[],suggestions:[]};
  const canManage=()=>['owner','admin','staff'].includes(window.profile?.role||'');
  const canEditRules=()=>['owner','admin'].includes(window.profile?.role||'');
  const month=()=>new Date().toISOString().slice(0,7)+'-01';
  const templates={
    overdue_fee:{title:'Fee reminder',body:'Dear {{guardian}}, {{student}} has an outstanding fee of {{balance}} for {{month}}. Please contact {{center}} if you need assistance.'},
    absent:{title:'Attendance reminder',body:'Dear {{guardian}}, {{student}} has missed {{count}} recent classes. Please check in with {{center}} if there is a reason for the absence.'},
    low_result:{title:'Academic progress reminder',body:'Dear {{guardian}}, {{student}} recently scored {{score}}% in {{exam}}. Please encourage a review plan with {{center}}.'}
  };
  async function load(){
    const org=window.orgId(); if(!org) throw new Error('Workspace is not ready.');
    const [r,e]=await Promise.all([
      window.client().from('reminder_rules').select('id,type,enabled,threshold,cooldown_days').eq('organization_id',org).order('type'),
      window.client().from('reminder_events').select('id,student_id,type,generated_at,campaign_id,students(name,guardian_name,guardian_phone)').eq('organization_id',org).order('generated_at',{ascending:false}).limit(100)
    ]);
    if(r.error)throw r.error;if(e.error)throw e.error;state.rules=r.data||[];state.events=e.data||[];state.suggestions=buildSuggestions();
  }
  function rule(type){return state.rules.find(r=>r.type===type)||{type,enabled:true,threshold:type==='low_result'?50:type==='absent'?3:1,cooldown_days:7};}
  function buildSuggestions(){
    const students=window.data?.students||[], out=[];
    const payByStudent=new Map(students.map(s=>[s.id,Number(s.paid||0)]));
    students.forEach(s=>{
      const bal=Math.max(0,Number(s.monthly_fee||0)-Number(payByStudent.get(s.id)||0));
      const rr=rule('overdue_fee'); if(rr.enabled&&bal>0) out.push({type:'overdue_fee',student:s,balance:bal,month:month()});
      const abs=(window.data?.attendance||[]).filter(a=>a.student_id===s.id&&!a.present).slice(0,10).length;
      const ar=rule('absent'); if(ar.enabled&&abs>=Number(ar.threshold||3)) out.push({type:'absent',student:s,count:abs});
      const latest=(window.data?.results||[]).find(r=>r.student_id===s.id); const score=latest?Math.round(Number(latest.marks||0)/Number(latest.exams?.total_marks||100)*100):null;
      const lr=rule('low_result'); if(lr.enabled&&score!==null&&score<Number(lr.threshold||50)) out.push({type:'low_result',student:s,score,exam:latest.exams?.name||'recent exam'});
    });
    return out.filter(x=>!recentlyGenerated(x.student.id,x.type,rule(x.type).cooldown_days));
  }
  function recentlyGenerated(studentId,type,cooldown){const cutoff=Date.now()-Number(cooldown||7)*86400000;return state.events.some(e=>e.student_id===studentId&&e.type===type&&new Date(e.generated_at).getTime()>=cutoff)}
  function personalize(item){const t=templates[item.type];return {title:t.title,body:t.body.replaceAll('{{guardian}}',item.student.guardian_name||'Guardian').replaceAll('{{student}}',item.student.name).replaceAll('{{balance}}',money(item.balance||0)).replaceAll('{{month}}',new Date(item.month||month()).toLocaleDateString('en-BD',{month:'long',year:'numeric'})).replaceAll('{{center}}',window.profile?.organizations?.name||'our coaching center').replaceAll('{{count}}',String(item.count||0)).replaceAll('{{score}}',String(item.score??0)).replaceAll('{{exam}}',item.exam||'recent exam')};}
  function view(){const summaries={overdue_fee:'Outstanding fee',absent:'Repeated absence',low_result:'Low exam result'};return `<div class="page-head"><div><h1>Reminders</h1><div class="subtitle">Generate safe, reviewable reminders from live EduFlow data.</div></div><div class="actions"><button class="btn btn-secondary" onclick="loadReminders()">↻ Refresh</button>${canManage()?'<button class="btn btn-primary" onclick="generateReminders()">Generate suggestions</button>':''}</div></div><div class="grid grid-3">${['overdue_fee','absent','low_result'].map(t=>`<div class="card"><div class="label">${summaries[t]}</div><div class="value">${state.suggestions.filter(x=>x.type===t).length}</div><div class="subtitle">Ready for review</div></div>`).join('')}</div><div class="card" style="margin-top:16px"><div class="section-head"><div><h2>Suggested reminders</h2><div class="subtitle">Nothing is sent automatically. Review and prepare a message first.</div></div><span class="badge badge-blue">${state.suggestions.length}</span></div><div class="table-wrap" style="margin-top:10px"><table><thead><tr><th>Type</th><th>Student</th><th>Guardian</th><th>Reason</th><th></th></tr></thead><tbody>${state.suggestions.map((x,i)=>`<tr><td><span class="badge ${x.type==='overdue_fee'?'badge-warning':x.type==='absent'?'badge-danger':'badge-blue'}">${esc(summaries[x.type])}</span></td><td><strong>${esc(x.student.name)}</strong><div class="subtitle">${esc(x.student.student_code)}</div></td><td>${esc(x.student.guardian_name||'—')}<div class="subtitle">${esc(x.student.guardian_phone||'—')}</div></td><td>${esc(reason(x))}</td><td><button class="btn btn-primary btn-sm" onclick="prepareReminder(${i})">Prepare</button></td></tr>`).join('')||'<tr><td colspan="5"><div class="empty">No reminders need attention right now.</div></td></tr>'}</tbody></table></div></div><div class="card" style="margin-top:16px"><h2>Rules</h2><div class="grid grid-3" style="margin-top:12px">${['overdue_fee','absent','low_result'].map(t=>ruleEditor(t)).join('')}</div></div>`;}
  function reason(x){if(x.type==='overdue_fee')return `${money(x.balance)} estimated outstanding`;if(x.type==='absent')return `${x.count} recent absences`;return `${x.score}% in ${x.exam}`;}
  function ruleEditor(type){const r=rule(type);const labels={overdue_fee:'Overdue fee',absent:'Absence threshold',low_result:'Low result threshold'};return `<div class="card" style="padding:14px"><strong>${labels[type]}</strong><div class="field" style="margin-top:10px"><label>Enabled</label><select id="rr_${type}"><option value="true" ${r.enabled?'selected':''}>Yes</option><option value="false" ${!r.enabled?'selected':''}>No</option></select></div><div class="field" style="margin-top:10px"><label>Threshold</label><input id="rt_${type}" type="number" min="1" value="${Number(r.threshold||1)}"></div><div class="field" style="margin-top:10px"><label>Cooldown days</label><input id="rc_${type}" type="number" min="1" value="${Number(r.cooldown_days||7)}"></div>${canEditRules()?'<button class="btn btn-secondary btn-sm" style="margin-top:10px" onclick="saveReminderRule(\''+type+'\')">Save rule</button>':''}</div>`;}
  async function generate(){await load();window.render();window.toast?.(`${state.suggestions.length} reminder suggestions ready.`);}
  async function prepareReminder(index){const x=state.suggestions[index];if(!x)return;const p=personalize(x);window.modal('Prepare reminder',`<div class="notice"><strong>${esc(x.student.guardian_name||'Guardian')}</strong> • ${esc(x.student.guardian_phone||'No phone')}</div><div class="field" style="margin-top:12px"><label>Title</label><input id="rem_title" value="${esc(p.title)}"></div><div class="field" style="margin-top:12px"><label>Message</label><textarea id="rem_body" rows="7">${esc(p.body)}</textarea></div><div class="actions end-actions"><button class="btn btn-secondary" onclick="copyReminder()">Copy message</button><button class="btn btn-primary" onclick="saveReminderCampaign(${index})">Save to communications</button></div>`);}
  async function copyReminder(){try{await navigator.clipboard.writeText(document.getElementById('rem_body').value);window.toast?.('Message copied.')}catch(e){window.toast?.('Copy failed. Select and copy the message manually.');}}
  async function saveReminderCampaign(index){try{if(!canManage())throw new Error('You do not have permission to prepare reminders.');const x=state.suggestions[index];const title=document.getElementById('rem_title').value.trim(),body=document.getElementById('rem_body').value.trim();if(!title||!body)throw new Error('Title and message are required.');const org=window.orgId();const {data:c,error:ce}=await window.client().from('communication_campaigns').insert({organization_id:org,title,body,channel:'whatsapp',audience_type:'student',status:'prepared'}).select('id').single();if(ce)throw ce;const {error:re}=await window.client().from('communication_recipients').insert({organization_id:org,campaign_id:c.id,student_id:x.student.id,recipient_name:x.student.guardian_name||'Guardian',recipient_phone:x.student.guardian_phone||x.student.phone,personalized_message:body,status:'prepared'});if(re)throw re;const {error:ee}=await window.client().from('reminder_events').insert({organization_id:org,student_id:x.student.id,type:x.type,campaign_id:c.id,dedupe_key:`${x.type}:${x.student.id}:${new Date().toISOString().slice(0,10)}`});if(ee && ee.code!=='23505')throw ee;window.closeModal();state.suggestions=state.suggestions.filter((_,i)=>i!==index);window.render();window.toast?.('Reminder saved to Communications.');}catch(e){window.toast?.(e.message);}}
  async function saveRule(type){if(!canEditRules())return window.toast?.('Only owners and admins can change reminder rules.');const payload={organization_id:window.orgId(),type,enabled:document.getElementById('rr_'+type).value==='true',threshold:Number(document.getElementById('rt_'+type).value||1),cooldown_days:Number(document.getElementById('rc_'+type).value||7)};const {error}=await window.client().from('reminder_rules').upsert(payload,{onConflict:'organization_id,type'});if(error)window.toast?.(error.message);else{await load();window.render();window.toast?.('Reminder rule saved.');}}
  const originalRender=window.render;
  window.render=function(){if(window.page==='reminders'){const c=document.getElementById('content');if(c){load().then(()=>{c.innerHTML=view();}).catch(e=>{c.innerHTML=`<div class="card"><div class="notice">${esc(e.message)}</div></div>`});}return;}return originalRender.apply(this,arguments);};
  Object.assign(window,{loadReminders:load,generateReminders:generate,prepareReminder,saveReminderCampaign,saveReminderRule:saveRule,copyReminder});
})();
