'use client'
import { useTransition } from 'react'
import { saveMeal } from '@/app/actions'

export default function MealTracker({ flatId, cycleId, userId, date, policy, initial }: { flatId:string; cycleId:string; userId:string; date:string; policy:'opt_in'|'opt_out'; initial: Record<string,number> }) {
  const [pending,start]=useTransition()
  const current=(type:'lunch'|'dinner'|'extra')=> initial[type] ?? (type==='extra'?0:policy==='opt_out'?1:0)
  const setMeal=(type:'lunch'|'dinner'|'extra',count:number)=>start(async()=>{ await saveMeal({flatId,cycleId,userId,date,mealType:type,count}); initial[type]=count })
  return <div className="grid gap-4 sm:grid-cols-2"><div className="card"><div className="mb-3 font-semibold">Lunch</div><div className="flex gap-2"><button className={current('lunch')>0?'btn-primary':'btn-secondary'} disabled={pending} onClick={()=>setMeal('lunch',1)}>I ate</button><button className={current('lunch')===0?'btn-primary':'btn-secondary'} disabled={pending} onClick={()=>setMeal('lunch',0)}>Skip</button></div><p className="mt-3 text-sm text-slate-500">Current count: {current('lunch')}</p></div><div className="card"><div className="mb-3 font-semibold">Dinner</div><div className="flex gap-2"><button className={current('dinner')>0?'btn-primary':'btn-secondary'} disabled={pending} onClick={()=>setMeal('dinner',1)}>I ate</button><button className={current('dinner')===0?'btn-primary':'btn-secondary'} disabled={pending} onClick={()=>setMeal('dinner',0)}>Skip</button></div><p className="mt-3 text-sm text-slate-500">Current count: {current('dinner')}</p></div><div className="card sm:col-span-2"><div className="mb-2 font-semibold">Extra / guest meals</div><div className="flex flex-wrap items-center gap-2"><button className="btn-secondary" disabled={pending} onClick={()=>setMeal('extra',Math.max(0,current('extra')-1))}>−</button><span className="min-w-10 text-center text-lg font-semibold">{current('extra')}</span><button className="btn-primary" disabled={pending} onClick={()=>setMeal('extra',current('extra')+1)}>+</button><span className="text-sm text-slate-500">Guests are attributed to the host member.</span></div></div></div>
}
